### ISSUE TITLE
Improvement: for a folder, opt to classify a (non-folder) default item therein

### ISSUE THREAD

**Issue by grahamperrin** [ggozad/collective.classification#1]
= Use case =

Text at http://www.brighton.ac.uk/centrim/research/projects/mental-models/folder_contents is minimal.

That folder defaults to view a page http://www.brighton.ac.uk/centrim/research/projects/mental-models/overview in which text is substantial. 

= Feature (improvement) =

http://www.brighton.ac.uk/centrim/research/projects/mental-models/@@subjectsuggest should: 
- detect that there is a default view for the folder
- offer an option, to make suggestions based on that item (not based upon the folder). 

A more exotic additional option would be to make suggestions based upon /both/ the folder /and/ its default item.

**Comment by ggozad** [comment]
closed by 2c7d0cc148006682431d49d31b67893bd630595c, error on control panel when saving
