### ISSUE TITLE
prefer @@suggest-categories to @@subjectsuggest

### ISSUE THREAD

**Issue by grahamperrin** [ggozad/collective.classification#2]
= Motivations =
1. Plone speak for developers may be 'subjects', but to everyday users of Plone 3.x, the expression is:

    categories

(Historically: the expression was 'keywords', but let's ignore that.)
1. Order the words in a more spoken way, e.g. speaking 'suggest categories' /sounds/ better than speaking 'categories suggest'.
2. Hyphenate, e.g. @@manage-portlets and @@manage-viewlets so for consistency, 

    @@suggest-categories

**Comment by ggozad** [comment]
renamed suggestsubject to follow proper naming convention, closed by ea08a9b19e167e5c627e3d0c777f5f3d5f6a7ae3
