### ISSUE TITLE
Error when selecting N-gram but no category

### ISSUE THREAD

**Issue by soerensigfusson** [ggozad/collective.classification#3]
As a default no category is selected so when you chose N-gram and press save, you will get the error:

Time    2010/03/02 11:17:05.890 GMT+1
User Name (User Id)  soren (soren)
Request URL http://localhost:8080/nordic/@@classifier-settings-controlpanel
Exception Type  ValueError
Exception Value concat() expects at least one object!
Traceback (innermost last):

Module plone.postpublicationhook.hook, line 74, in publish
Module ZPublisher.mapply, line 88, in mapply
Module ZPublisher.Publish, line 42, in call_object
Module zope.formlib.form, line 769, in **call**
Module Products.Five.formlib.formbase, line 55, in update
Module zope.formlib.form, line 750, in update
Module zope.formlib.form, line 594, in success
Module collective.classification.browser.controlpanel, line 153, in save_action
Module nltk.corpus.reader.tagged, line 211, in tagged_sents
Module nltk.corpus.reader.tagged, line 148, in tagged_sents
Module nltk.corpus.reader.util, line 412, in concat
ValueError: concat() expects at least one object!

**Comment by ggozad** [comment]
Have to specify corpus categories when training n-gram tagger. Closed by 37545d17b1a642372cc2eca4dfc3bc131d6d2f05
