### ISSUE TITLE
Confusing status message after reparsing

### ISSUE THREAD

**Issue by soerensigfusson** [ggozad/collective.classification#4]
After you have pressed "Reparse all documents", the status info show "Term extractor trained and NP storage updated. You will need to re-train the classifier as well."

The first sentece is left-over from previous release, and isn't that usefriendly. Maybe it should just say: "Documents reparsed. You will need to re-train the classifier as well."

**Comment by ggozad** [comment]
ambiguous message replaced, closed by 883279a53a7ec33421706a48c0d614c5fb356b1c
